export type ProjectStatus = "concept" | "client";

export type PortfolioProject = {
  id: string; slug: string; title: string; status: ProjectStatus; category: string; summary: string; description: string; href: string;
  challenge: string[]; approach: string[]; deliverables: string[]; capabilities: string[]; technologies: string[];
  limitations: string[]; relatedProjectIds: string[]; seo: { title: string; description: string };
};

const concept = (project: Omit<PortfolioProject, "status" | "href" | "technologies">): PortfolioProject => ({
  ...project, status: "concept", href: `/realisations/${project.slug}`, technologies: [],
});

export const portfolioProjects: PortfolioProject[] = [
  concept({ id:"garage", slug:"site-web-garage-local", title:"Site web pour garage local", category:"Site web", summary:"Concept de site vitrine structurant les services, les demandes de rendez-vous et l’information locale.", description:"Un scénario de conception destiné à montrer comment une entreprise de services locale pourrait clarifier son offre et faciliter une première prise de contact.", challenge:["Présenter clairement des services variés.","Rendre la prise de contact simple sur mobile.","Organiser une information locale crédible sans faux avis ni chiffres."], approach:["Hiérarchie centrée sur les besoins des automobilistes.","Parcours court entre service et demande.","Composants responsive et contenus faciles à parcourir."], deliverables:["Architecture de pages","Écrans de service","Parcours de demande","Composants responsive"], capabilities:["Architecture web","Contenu structuré","Responsive","Formulaires"], limitations:["Concept non commandé par un garage.","Aucun résultat commercial mesuré.","Aucun contenu client réel intégré."], relatedProjectIds:["reservation","gestion"], seo:{title:"Concept de site web pour garage local",description:"Concept démonstratif de site web pour un garage local, centré sur les services et la prise de contact."} }),
  concept({ id:"reservation", slug:"plateforme-reservation", title:"Plateforme de réservation", category:"Application web", summary:"Concept de plateforme réunissant disponibilités, demandes et confirmations dans un parcours cohérent.", description:"Ce concept explore une expérience de réservation destinée à réduire la dispersion des demandes entre téléphone et messages.", challenge:["Regrouper les disponibilités et les demandes.","Rendre les statuts compréhensibles.","Prévoir les exceptions sans alourdir le parcours."], approach:["Parcours organisé autour du choix d’un créneau.","États explicites pour les confirmations.","Séparation entre expérience publique et gestion interne."], deliverables:["Parcours de réservation","Calendrier conceptuel","États de confirmation","Vue de gestion"], capabilities:["UX transactionnelle","Interfaces métier","Gestion d’états","Responsive"], limitations:["Concept sans exploitant réel.","Aucune intégration de calendrier confirmée.","Aucune donnée d’usage disponible."], relatedProjectIds:["garage","mobile"], seo:{title:"Concept de plateforme de réservation",description:"Concept démonstratif d’une plateforme web de réservation et de gestion des disponibilités."} }),
  concept({ id:"gestion", slug:"application-gestion-interne", title:"Application de gestion interne", category:"Application web", summary:"Concept d’outil métier centralisant clients, tâches, documents et statuts opérationnels.", description:"Un scénario d’application interne conçu pour illustrer la structuration d’informations aujourd’hui dispersées.", challenge:["Réunir plusieurs sources d’information.","Différencier les rôles et responsabilités.","Maintenir un historique compréhensible."], approach:["Tableau de bord orienté actions.","Organisation par dossiers et statuts.","Accès et permissions à cadrer avant réalisation."], deliverables:["Tableau de bord","Fiches de suivi","Parcours par rôle","Historique conceptuel"], capabilities:["Outils métier","Gestion de données","Rôles","Tableaux de bord"], limitations:["Concept sans organisation cliente.","Modèle de données non validé sur le terrain.","Sécurité à spécifier selon les données réelles."], relatedProjectIds:["reservation","dashboard"], seo:{title:"Concept d’application de gestion interne",description:"Concept démonstratif d’une application métier pour centraliser tâches, documents et suivis."} }),
  concept({ id:"automation", slug:"automatisation-administrative", title:"Automatisation administrative", category:"Automatisation", summary:"Concept de flux reliant formulaire, classement, notification et tableau de suivi.", description:"Ce concept illustre comment un processus administratif répétitif pourrait être cartographié avant une automatisation encadrée.", challenge:["Éviter les doubles saisies.","Rendre les erreurs et exceptions visibles.","Conserver des validations humaines."], approach:["Cartographie du flux avant outillage.","Points de contrôle explicites.","Journal de suivi pour comprendre chaque étape."], deliverables:["Carte du processus","Scénarios de flux","Points de contrôle","Documentation conceptuelle"], capabilities:["Automatisation","Processus","Notifications","Documentation"], limitations:["Aucun gain de temps mesuré.","Aucun outil tiers confirmé.","Les décisions sensibles restent humaines."], relatedProjectIds:["gestion","dashboard"], seo:{title:"Concept d’automatisation administrative",description:"Concept démonstratif d’un flux administratif automatisé avec contrôles humains."} }),
  concept({ id:"dashboard", slug:"tableau-bord-pme", title:"Tableau de bord PME", category:"SaaS", summary:"Concept de tableau de bord donnant une lecture commune des demandes, tâches et indicateurs choisis.", description:"Une exploration d’interface pour aider une équipe à consulter ses activités sans présenter de données ou résultats réels.", challenge:["Prioriser peu d’indicateurs utiles.","Rendre les filtres compréhensibles.","Éviter une lecture trompeuse des données."], approach:["Hiérarchie par décision à prendre.","Filtres et états vides explicites.","Visualisations sobres et secondaires."], deliverables:["Vue synthèse","Filtres conceptuels","États de données","Structure modulaire"], capabilities:["Visualisation de données","SaaS","Filtres","Architecture modulaire"], limitations:["Aucune donnée d’entreprise utilisée.","Aucun indicateur de performance validé.","Concept sans produit commercialisé."], relatedProjectIds:["gestion","automation"], seo:{title:"Concept de tableau de bord pour PME",description:"Concept démonstratif de tableau de bord pour structurer le suivi d’activités d’une PME."} }),
  concept({ id:"mobile", slug:"application-mobile-service-local", title:"Application mobile pour service local", category:"Application mobile", summary:"Concept mobile pour déposer une demande, consulter son statut et recevoir des informations utiles.", description:"Ce scénario explore une relation de service sur téléphone sans prétendre représenter une application publiée.", challenge:["Réduire les étapes d’une demande mobile.","Rendre le statut immédiatement compréhensible.","Prévoir les notifications sans dépendance excessive."], approach:["Navigation courte adaptée au pouce.","États et prochaines actions visibles.","Progression conçue pour les petits écrans."], deliverables:["Parcours mobile","Écrans de demande","Suivi de statut","États de notification"], capabilities:["UX mobile","Parcours de service","Notifications","Accessibilité"], limitations:["Prototype visuel non publié en boutique.","Aucun utilisateur client testé.","Aucune technologie mobile arrêtée."], relatedProjectIds:["reservation","garage"], seo:{title:"Concept d’application mobile de service local",description:"Concept démonstratif d’application mobile pour demandes et suivis d’un service local."} }),
];

export const projectStatusLabels: Record<ProjectStatus,string> = {concept:"CONCEPT DÉMONSTRATIF",client:"PROJET CLIENT"};
export const getPortfolioProject=(slug:string)=>portfolioProjects.find((project)=>project.slug===slug);
export const getRelatedProjects=(project:PortfolioProject)=>project.relatedProjectIds.map(id=>portfolioProjects.find(item=>item.id===id)).filter((item):item is PortfolioProject=>Boolean(item));
