import {useContent} from "@/i18n/content";
import Link from "@/components/localized-link";
import { ArrowLeft, ArrowRight, Check, ChevronRight, Network } from "lucide-react";
import { BadgeConcept } from "@/components/badge-concept";
import type { PortfolioProject } from "@/lib/project-portfolio";
import { getRelatedProjects } from "@/lib/project-portfolio";

export function ProjectVisual({ compact=false }: { compact?: boolean }) {
  const m = useContent();
 return <div role="img" aria-label={m.common.projectVisual} className={`relative overflow-hidden border border-bg-800 bg-bg-950 ${compact?"h-40":"min-h-72"}`}><div className="absolute inset-6 border border-purple-500/30"/><div className="absolute left-1/2 top-0 h-full w-px bg-bg-800"/><div className="absolute left-0 top-1/2 h-px w-full bg-bg-800"/><Network className="absolute left-1/2 top-1/2 h-8 w-8 -translate-x-1/2 -translate-y-1/2 text-purple-300" aria-hidden="true"/></div>; }

export function ProjectCard({project,index}:{project:PortfolioProject;index:number}) {
  const m = useContent();
 return <article className="flex h-full flex-col rounded-sm border border-bg-800 bg-bg-900 p-5"><div className="flex items-start justify-between gap-4"><BadgeConcept/><span className="font-mono text-xs text-text-400">0{index+1}</span></div><div className="mt-6"><ProjectVisual compact/></div><p className="mt-6 font-mono text-xs uppercase tracking-[.18em] text-purple-300">{project.category}</p><h2 className="mt-3 text-2xl font-semibold">{project.title}</h2><p className="mt-4 flex-1 text-sm leading-6 text-text-400">{project.summary}</p><div className="mt-5 flex flex-wrap gap-2">{project.capabilities.slice(0,3).map(item=><span key={item} className="border border-bg-800 px-2 py-1 text-xs text-text-400">{item}</span>)}</div><Link href={project.href} className="mt-7 inline-flex min-h-11 items-center gap-2 font-semibold text-purple-300">{m.portfolio.listing.exploreConcept} <ArrowRight className="h-4 w-4" aria-hidden="true"/></Link></article>; }

export function ProjectBreadcrumb({project}:{project:PortfolioProject}) {
  const m = useContent();
 return <nav aria-label={m.common.breadcrumb}><ol className="flex flex-wrap items-center gap-2 text-sm text-text-400"><li><Link href="/" className="inline-flex min-h-11 items-center">{m.navigation.items.home}</Link></li><li aria-hidden="true"><ChevronRight className="h-4 w-4"/></li><li><Link href="/realisations" className="inline-flex min-h-11 items-center">{m.navigation.items.portfolio}</Link></li><li aria-hidden="true"><ChevronRight className="h-4 w-4"/></li><li><span aria-current="page" className="inline-flex min-h-11 items-center text-text-100">{project.title}</span></li></ol></nav>; }

export function ProjectDetail({project}:{project:PortfolioProject}) {
  const m = useContent();
 const related=getRelatedProjects(project); return <>
  <section className="border-b border-bg-800"><div className="mx-auto max-w-(--container-max) px-4 py-8 sm:px-6 lg:px-8"><ProjectBreadcrumb project={project}/><div className="grid gap-10 py-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><BadgeConcept/><p className="mt-6 font-mono text-xs uppercase tracking-[.18em] text-purple-300">{project.category}</p><h1 className="mt-4 text-4xl font-bold tracking-[-.035em] sm:text-5xl lg:text-6xl">{project.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-text-400">{project.summary}</p><div className="mt-6 flex flex-wrap gap-2">{project.capabilities.map(item=><span key={item} className="border border-bg-800 px-3 py-2 text-xs text-text-400">{item}</span>)}</div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/contact#devis" className="inline-flex min-h-11 items-center justify-center gap-2 bg-purple-600 px-5 py-3 font-semibold text-[#f4f1ea]">{m.portfolio.detail.presentNeed} <ArrowRight className="h-4 w-4" aria-hidden="true"/></Link><Link href="/realisations" className="inline-flex min-h-11 items-center justify-center gap-2 border border-bg-800 px-5 py-3 font-semibold"><ArrowLeft className="h-4 w-4" aria-hidden="true"/>{m.home.concepts.allConcepts}</Link></div></div><ProjectVisual/></div></div></section>
  <section className="border-b border-bg-800 py-20"><div className="mx-auto grid max-w-(--container-max) gap-10 px-4 sm:px-6 lg:grid-cols-[.75fr_1.25fr] lg:px-8"><div><p className="font-mono text-xs uppercase tracking-[.18em] text-purple-300">{m.portfolio.detail.contextEyebrow}</p><h2 className="mt-4 text-3xl font-semibold">{m.portfolio.detail.contextTitle}</h2><p className="mt-5 leading-7 text-text-400">{project.description}</p></div><div><h2 className="text-2xl font-semibold">{m.portfolio.detail.challengeTitle}</h2><ul className="mt-6 grid gap-3">{project.challenge.map(item=><li key={item} className="flex gap-3 border-b border-bg-800 pb-3"><Check className="mt-1 h-4 w-4 text-purple-300" aria-hidden="true"/>{item}</li>)}</ul></div></div></section>
  <section className="border-b border-bg-800 bg-bg-900/40 py-20"><div className="mx-auto max-w-(--container-max) px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-semibold">{m.portfolio.detail.approachTitle}</h2><div className="mt-8 grid gap-px bg-bg-800 md:grid-cols-3">{project.approach.map((item,i)=><article key={item} className="bg-bg-950 p-6"><span className="font-mono text-xs text-purple-300">0{i+1}</span><p className="mt-6 leading-7">{item}</p></article>)}</div></div></section>
  <section className="border-b border-bg-800 py-20"><div className="mx-auto grid max-w-(--container-max) gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div><h2 className="text-3xl font-semibold">{m.portfolio.detail.deliverablesTitle}</h2><ul className="mt-7 grid gap-3">{project.deliverables.map(item=><li key={item} className="flex gap-3"><Check className="mt-1 h-4 w-4 text-purple-300" aria-hidden="true"/>{item}</li>)}</ul></div><div><h2 className="text-3xl font-semibold">{m.portfolio.detail.limitationsTitle}</h2><ul className="mt-7 grid gap-3">{project.limitations.map(item=><li key={item} className="border-l border-purple-500 pl-4 text-text-400">{item}</li>)}</ul></div></div></section>
  <section className="border-b border-bg-800 bg-bg-900/30 py-20"><div className="mx-auto max-w-(--container-max) px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-semibold">{m.portfolio.detail.relatedTitle}</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{related.map((item,i)=><ProjectCard key={item.id} project={item} index={i}/>)}</div></div></section>
  <section className="py-16"><div className="mx-auto max-w-(--container-max) px-4 sm:px-6 lg:px-8"><div className="bg-purple-600 p-8 text-[#f4f1ea] sm:p-12"><p className="font-mono text-xs uppercase tracking-[.18em]">{m.portfolio.detail.differentContext}</p><h2 className="mt-4 max-w-3xl text-3xl font-semibold sm:text-4xl">{m.portfolio.detail.ctaTitle}</h2><Link href="/contact#devis" className="mt-7 inline-flex min-h-11 items-center gap-2 bg-bg-950 px-5 py-3 font-semibold text-text-100">{m.portfolio.detail.ctaSubmit} <ArrowRight className="h-4 w-4" aria-hidden="true"/></Link></div></div></section>
  </>; }
