import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, CircleDot, MapPin, MessageSquareText, Minus } from "lucide-react";
import { aboutMethod, aboutPrinciples, aboutScope } from "@/lib/about-content";

export const metadata: Metadata = {
  title: "À propos d’Infotechs Solutions",
  description: "Découvrez l’approche d’Infotechs Solutions pour concevoir des sites web, automatisations et applications métier adaptés aux PME et organisations.",
  alternates: { canonical: "/a-propos" },
  openGraph: {
    title: "À propos d’Infotechs Solutions",
    description: "Une approche directe et progressive pour cadrer et concevoir des solutions numériques adaptées aux besoins réels.",
    url: "/a-propos",
  },
};

function CollaborationMap() {
  return <div role="img" aria-label="La collaboration relie le contexte, les décisions et une solution vérifiable" className="relative min-h-72 overflow-hidden rounded-sm border border-bg-800 bg-bg-900/80 p-6 sm:p-8">
    <div className="absolute inset-0 opacity-40 [background-image:linear-gradient(rgba(226,121,61,.08)_1px,transparent_1px),linear-gradient(90deg,rgba(226,121,61,.08)_1px,transparent_1px)] [background-size:40px_40px]" aria-hidden="true" />
    <div className="relative grid h-full min-h-56 grid-cols-[1fr_auto_1fr] items-center gap-3">
      <div className="space-y-3"><span className="block border border-bg-800 bg-bg-950 p-3 text-sm">Contexte</span><span className="block border border-bg-800 bg-bg-950 p-3 text-sm">Utilisateurs</span><span className="block border border-bg-800 bg-bg-950 p-3 text-sm">Contraintes</span></div>
      <div className="flex items-center gap-2 text-copper-500" aria-hidden="true"><Minus className="h-5 w-5" /><CircleDot className="h-9 w-9" /><Minus className="h-5 w-5" /></div>
      <div className="border border-copper-500 bg-copper-500/10 p-4 text-center text-sm font-semibold">Décisions<br />vérifiables</div>
    </div>
  </div>;
}

export default function AboutPage() {
  return <>
    <section className="relative overflow-hidden border-b border-bg-800"><div className="mx-auto grid max-w-(--container-max) gap-12 px-4 py-20 sm:px-6 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:px-8 lg:py-24"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-copper-500">À propos · approche directe</p><h1 className="mt-5 max-w-4xl text-4xl font-bold tracking-[-.035em] sm:text-5xl lg:text-6xl">Des solutions numériques cadrées autour de vos besoins réels.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-text-400">Infotechs Solutions accompagne les PME et organisations dans la conception de sites web, d’automatisations ciblées et d’applications métier. La clarification précède la technologie, puis chaque étape produit des décisions que vous pouvez vérifier.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/contact#devis" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-sm bg-copper-500 px-5 py-3 font-semibold text-[#14151a]">Présenter votre besoin <ArrowRight className="h-4 w-4" aria-hidden="true" /></Link><a href="#methode" className="inline-flex min-h-11 items-center justify-center rounded-sm border border-bg-800 px-5 py-3 font-semibold hover:border-copper-500">Voir la méthode</a></div></div><CollaborationMap /></div></section>

    <section className="border-b border-bg-800 py-20"><div className="mx-auto grid max-w-(--container-max) gap-10 px-4 sm:px-6 lg:grid-cols-[.72fr_1.28fr] lg:px-8"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-copper-500">Raison d’être</p><h2 className="mt-4 text-3xl font-semibold sm:text-4xl">Clarifier le problème avant d’élargir la solution.</h2></div><div className="max-w-3xl space-y-6 text-lg leading-8 text-text-400"><p>Un besoin numérique arrive souvent avec plusieurs idées de fonctionnalités, d’outils ou d’intégrations. Commencer par la technologie peut rendre le projet plus complexe sans résoudre le bon problème.</p><p>Infotechs Solutions privilégie une intention actuelle : comprendre ce qui freine les opérations, choisir un niveau de solution adapté, puis avancer par livraisons vérifiables. Toutes les organisations n’ont ni les mêmes usages, ni les mêmes contraintes, ni besoin du même système.</p></div></div></section>

    <section className="border-b border-bg-800 bg-bg-900/35 py-20"><div className="mx-auto max-w-(--container-max) px-4 sm:px-6 lg:px-8"><p className="font-mono text-xs uppercase tracking-[.2em] text-copper-500">Principes de travail</p><h2 className="mt-4 max-w-3xl text-3xl font-semibold sm:text-4xl">Des principes traduits en comportements concrets.</h2><div className="mt-10 grid gap-px overflow-hidden rounded-sm border border-bg-800 bg-bg-800 md:grid-cols-2 lg:grid-cols-3">{aboutPrinciples.map((principle, index) => <article key={principle.id} className="bg-bg-950 p-6 sm:p-7"><span className="font-mono text-xs text-copper-500">0{index + 1}</span><h3 className="mt-7 text-xl font-semibold">{principle.title}</h3><p className="mt-3 leading-7 text-text-400">{principle.description}</p></article>)}</div></div></section>

    <section id="methode" className="scroll-mt-24 border-b border-bg-800 py-20"><div className="mx-auto max-w-(--container-max) px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="font-mono text-xs uppercase tracking-[.2em] text-copper-500">Méthode de collaboration</p><h2 className="mt-4 text-3xl font-semibold sm:text-4xl">Un chemin lisible, avec des validations à chaque étape.</h2><p className="mt-5 leading-7 text-text-400">Le client peut attendre des échanges structurés, des décisions documentées et une communication transparente sur les limites. Une étape n’est pas présentée comme acquise avant d’avoir été vérifiée.</p></div><ol className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{aboutMethod.map(step => <li key={step.number} className="border-l border-copper-500 py-2 pl-6"><span className="font-mono text-xs text-copper-500">{step.number}</span><h3 className="mt-4 text-xl font-semibold">{step.title}</h3><p className="mt-3 leading-7 text-text-400">{step.description}</p></li>)}</ol></div></section>

    <section className="border-b border-bg-800 bg-bg-900/35 py-20"><div className="mx-auto max-w-(--container-max) px-4 sm:px-6 lg:px-8"><p className="font-mono text-xs uppercase tracking-[.2em] text-copper-500">Périmètre responsable</p><h2 className="mt-4 max-w-3xl text-3xl font-semibold sm:text-4xl">Ce que nous pouvons concevoir — et ce que le cadrage doit préciser.</h2><div className="mt-10 grid gap-6 lg:grid-cols-2"><article className="border border-bg-800 bg-bg-950 p-6 sm:p-8"><h3 className="text-xl font-semibold">Infotechs Solutions peut notamment</h3><ul className="mt-6 space-y-4">{aboutScope.canDo.map(item => <li key={item} className="flex gap-3 leading-7 text-text-400"><Check className="mt-1 h-5 w-5 shrink-0 text-copper-500" aria-hidden="true" />{item}</li>)}</ul></article><article className="border border-bg-800 bg-bg-950 p-6 sm:p-8"><h3 className="text-xl font-semibold">Le cadrage doit déterminer</h3><ul className="mt-6 space-y-4">{aboutScope.needsScoping.map(item => <li key={item} className="flex gap-3 leading-7 text-text-400"><CircleDot className="mt-1 h-5 w-5 shrink-0 text-copper-500" aria-hidden="true" />{item}</li>)}</ul><p className="mt-6 border-t border-bg-800 pt-5 text-sm leading-6 text-text-400">Les besoins spécialisés ne sont pas écartés : ils demandent une évaluation explicite et, selon le cas, des compétences complémentaires.</p></article></div></div></section>

    <section className="border-b border-bg-800 py-20"><div className="mx-auto grid max-w-(--container-max) gap-8 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><article className="border-t border-copper-500 pt-7"><MessageSquareText className="h-7 w-7 text-copper-500" aria-hidden="true" /><p className="mt-6 font-mono text-xs uppercase tracking-[.2em] text-copper-500">Une collaboration humaine</p><h2 className="mt-4 text-3xl font-semibold">Un échange direct, du cadrage à la mise en service.</h2><p className="mt-5 leading-7 text-text-400">La disponibilité, la clarté des échanges et la responsabilité sur les décisions priment sur une présentation d’équipe artificielle. Le suivi porte sur ce qui a été compris, décidé, livré et reste à valider.</p></article><article className="border-t border-bg-800 pt-7"><MapPin className="h-7 w-7 text-copper-500" aria-hidden="true" /><p className="mt-6 font-mono text-xs uppercase tracking-[.2em] text-copper-500">Territoire</p><h2 className="mt-4 text-3xl font-semibold">Ancrée à Saint-Louis-de-Gonzague, en Montérégie.</h2><p className="mt-5 leading-7 text-text-400">Infotechs Solutions développe des solutions numériques pour les PME et organisations du Québec. Cette localisation décrit un ancrage; elle ne prétend ni à un bureau ouvert au public ni à une couverture géographique non documentée.</p></article></div></section>

    <section className="border-b border-bg-800 bg-bg-900/35 py-20"><div className="mx-auto grid max-w-(--container-max) gap-8 px-4 sm:px-6 lg:grid-cols-[1fr_auto] lg:items-end lg:px-8"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-copper-500">Preuves disponibles</p><h2 className="mt-4 max-w-3xl text-3xl font-semibold sm:text-4xl">Consulter l’offre et les scénarios sans confondre démonstration et mandat.</h2><p className="mt-5 max-w-3xl leading-7 text-text-400">Les concepts démonstratifs du portfolio illustrent des méthodes de conception et des scénarios fonctionnels. Ils ne sont pas présentés comme des mandats clients.</p></div><div className="flex flex-col gap-3 sm:flex-row"><Link href="/services" className="inline-flex min-h-11 items-center justify-center border border-bg-800 px-5 py-3 font-semibold hover:border-copper-500">Voir les services</Link><Link href="/realisations" className="inline-flex min-h-11 items-center justify-center gap-2 text-copper-500 font-semibold">Explorer les concepts <ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></div></div></section>

    <section className="py-16"><div className="mx-auto max-w-(--container-max) px-4 sm:px-6 lg:px-8"><div className="rounded-sm bg-copper-500 px-6 py-10 text-[#14151a] sm:px-10 lg:px-12 lg:py-12"><h2 className="max-w-4xl text-3xl font-semibold sm:text-4xl">Commençons par votre contexte, vos utilisateurs et vos priorités.</h2><p className="mt-4 max-w-2xl leading-7 text-black/70">Présentez le problème, les contraintes connues et ce qui doit être clarifié. La solution viendra ensuite.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Link href="/contact#devis" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-sm bg-bg-950 px-5 py-3 font-semibold text-text-100">Présenter votre besoin <ArrowRight className="h-4 w-4" aria-hidden="true" /></Link><Link href="/services" className="inline-flex min-h-11 items-center justify-center px-5 py-3 font-semibold">Revoir les services</Link></div></div></div></section>
  </>;
}
