import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Boxes, Database, LayoutDashboard, Smartphone, Workflow } from "lucide-react";
import { ProjectCard } from "@/components/project-experience";
import { portfolioProjects } from "@/lib/project-portfolio";

export const metadata:Metadata={title:"Concepts de projets numériques",description:"Portfolio de concepts démonstratifs illustrant des architectures web, outils métier, automatisations et expériences mobiles.",alternates:{canonical:"/realisations"},openGraph:{title:"Concepts de projets numériques | Infotechs Solutions",description:"Six concepts clairement identifiés comme démonstratifs.",url:"/realisations"}};
const capabilities=[[LayoutDashboard,"Interfaces métier"],[Database,"Gestion de données"],[Workflow,"Automatisation"],[Smartphone,"Expériences mobiles"],[Boxes,"Architecture modulaire"]] as const;
export default function RealisationsPage(){return <>
<section className="relative overflow-hidden border-b border-bg-800"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(101,40,255,.08)_1px,transparent_1px),linear-gradient(90deg,rgba(101,40,255,.08)_1px,transparent_1px)] [background-size:48px_48px]" aria-hidden="true"/><div className="relative mx-auto max-w-(--container-max) px-4 py-20 sm:px-6 lg:px-8 lg:py-24"><p className="font-mono text-xs uppercase tracking-[.2em] text-purple-300">Portfolio transparent</p><h1 className="mt-5 max-w-4xl text-4xl font-bold tracking-[-.035em] sm:text-5xl lg:text-6xl">Des concepts pour rendre les décisions numériques visibles.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-text-400">Ce portfolio présente des scénarios de conception, pas des mandats clients. Chaque fiche distingue ce qui est exploré, démontré et encore à valider.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/contact#devis" className="inline-flex min-h-11 items-center justify-center gap-2 bg-purple-600 px-5 py-3 font-semibold text-[#f4f1ea]">Présenter votre contexte <ArrowRight className="h-4 w-4" aria-hidden="true"/></Link><a href="#concepts" className="inline-flex min-h-11 items-center justify-center border border-bg-800 px-5 py-3 font-semibold">Explorer les concepts</a></div></div></section>
<section id="concepts" className="border-b border-bg-800 py-20"><div className="mx-auto max-w-(--container-max) px-4 sm:px-6 lg:px-8"><p className="font-mono text-xs uppercase tracking-[.2em] text-purple-300">Six scénarios</p><h2 className="mt-4 text-3xl font-semibold sm:text-4xl">Une lecture honnête de ce que chaque concept démontre.</h2><div className="mt-10 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{portfolioProjects.map((project,index)=><ProjectCard key={project.id} project={project} index={index}/>)}</div></div></section>
<section className="border-b border-bg-800 bg-bg-900/40 py-20"><div className="mx-auto max-w-(--container-max) px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-semibold">Lecture par capacité</h2><div className="mt-8 grid gap-px bg-bg-800 sm:grid-cols-2 lg:grid-cols-5">{capabilities.map(([Icon,label])=><div key={label} className="bg-bg-950 p-6"><Icon className="h-6 w-6 text-purple-300" aria-hidden="true"/><h3 className="mt-8 font-semibold">{label}</h3></div>)}</div></div></section>
<section className="border-b border-bg-800 py-20"><div className="mx-auto max-w-(--container-max) px-4 sm:px-6 lg:px-8"><h2 className="text-3xl font-semibold">De l’hypothèse à une version vérifiable.</h2><ol className="mt-10 grid gap-4 md:grid-cols-6">{["Comprendre","Cadrer","Prototyper","Construire","Valider","Faire évoluer"].map((item,i)=><li key={item} className="border-t border-purple-500 pt-5"><span className="font-mono text-xs text-purple-300">0{i+1}</span><h3 className="mt-5 font-semibold">{item}</h3></li>)}</ol></div></section>
<section className="py-16"><div className="mx-auto max-w-(--container-max) px-4 sm:px-6 lg:px-8"><div className="bg-purple-600 p-8 text-[#f4f1ea] sm:p-12"><h2 className="max-w-3xl text-3xl font-semibold sm:text-4xl">Votre projet commence par un contexte, pas par une démonstration.</h2><p className="mt-4 max-w-2xl leading-7 text-white/85">Décrivez le problème, les utilisateurs et les priorités à clarifier.</p><Link href="/contact#devis" className="mt-7 inline-flex min-h-11 items-center gap-2 bg-bg-950 px-5 py-3 font-semibold text-text-100">Présenter votre besoin <ArrowRight className="h-4 w-4" aria-hidden="true"/></Link></div></div></section></>}
